teams:
  Group A:
    - Germany
    - Scotland
    - Hungary
    - Switzerland
  Group B:
    - Spain
    - Croatia
    - Italy
    - Albania
  Group C:
    - Slovenia
    - Denmark
    - Serbia
    - England
  Group D:
    - Poland
    - Netherlands
    - Austria
    - France
  Group E:
    - Belgium
    - Slovakia
    - Romania
    - Ukraine
  Group F:
    - Turkey
    - Georgia
    - Portugal
    - Czechia
look_back_months: 36
home_advantage: 0.1
home_team: Germany