home_advantage: 0.9
home_team: Germany
look_back_months: 53
weighted_win_percentage_weight: 1.9
teams:
  Group A:
  - Germany
  - Scotland
  - Hungary
  - Switzerland
  Group B:
  - Spain
  - Croatia
  - Italy
  - Albania
  Group C:
  - Slovenia
  - Denmark
  - Serbia
  - England
  Group D:
  - Poland
  - Netherlands
  - Austria
  - France
  Group E:
  - Belgium
  - Slovakia
  - Romania
  - Ukraine
  Group F:
  - Turkey
  - Georgia
  - Portugal
  - Czechia
